# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'Canvas-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Socket.IO-Client-Swift', '~> 16.0.1'

end
